first commit: model and controller
calblueprint/dream-rails pull request #5
Opened 2017-10-07 01:39 UTC by melodywei861016

2017-10-09 22:19 UTC, loischang requested changes
you're doing great melody :)
remember to edit your routes for students!

2017-10-09 22:19 UTC, loischang commented on app/controllers/api/students_controller.rb
> +  			render json: course
student, not course

2017-10-09 22:19 UTC, loischang commented on app/controllers/api/students_controller.rb
> +
missing an end statement

2017-10-09 22:19 UTC, loischang commented on app/models/student.rb
> +  belongs_to :teacher
the teacher model isn't merged in yet

2017-10-09 22:19 UTC, loischang commented on app/views/students/edit.html.erb
> +<h1>Edit student</h1>
currently don't need edit view since that'll be done in react native ~

2017-10-09 22:19 UTC, loischang commented on app/models/student.rb
> +  enum emergency_contact:[
maybe make phone number and emergency contact name an attribute under student instead of enum?

2017-10-09 22:19 UTC, loischang commented on app/controllers/api/students_controller.rb
> +	def create
create currently doesn't save into the database :C

2017-10-11 21:55 UTC, charlesx2013 commented on app/assets/javascripts/students.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
remove

2017-10-11 21:55 UTC, charlesx2013 commented on app/assets/stylesheets/students.scss
> +// Place all the styles related to the Students controller here.
remove

2017-10-11 21:55 UTC, charlesx2013 commented on app/controllers/api/students_controller.rb
> +	def index
2 spaces, not four

2017-10-11 21:55 UTC, charlesx2013 commented on app/controllers/api/students_controller.rb
> +			params.require(:student).permit(:first_name, :last_name, :birthday, :year, :address, :nickname)
nit: line too long

2017-10-11 21:55 UTC, charlesx2013 commented on app/helpers/students_helper.rb
> +module StudentsHelper
remove

2017-10-14 00:59 UTC, caseytakahashi reviewed
A few nits to clean up unused files. Great job!

2017-10-14 00:59 UTC, caseytakahashi commented on app/views/teachers/_form.html.erb
> +<%= form_with(model: @teacher) do |form| %>
Delete all views created

2017-10-14 00:59 UTC, caseytakahashi commented on app/views/teachers/_form.html.erb
> +<%= form_with(model: @teacher) do |form| %>
(it looks like 5 were created)

2017-10-14 00:59 UTC, caseytakahashi commented on app/controllers/teachers_controller.rb
> +class TeachersController < ApplicationController
Move to app/controllers/api folder!

2017-10-16 18:28 UTC, loischang approved these changes

2017-10-16 18:29 UTC, loischang commented
GREAT JOB MELODY :D

2017-10-16 18:29 UTC, merged